//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbcng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat
    {
        public cat()
        {
            this.cats1 = new HashSet<cat>();
            this.products = new HashSet<product>();
        }
    
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public string cat_url { get; set; }
        public Nullable<int> cat_pos { get; set; }
        public Nullable<int> cat_parent_id { get; set; }
    
        public virtual ICollection<cat> cats1 { get; set; }
        public virtual cat cat1 { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
