//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbcng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_order
    {
        public long id { get; set; }
        public string customer_name { get; set; }
        public string customer_email { get; set; }
        public string customer_phone { get; set; }
        public string customer_address { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<long> product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> product_price { get; set; }
        public Nullable<double> product_total { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
