//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tbcng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ship
    {
        public int id { get; set; }
        public Nullable<int> g_from { get; set; }
        public Nullable<int> g_to { get; set; }
        public Nullable<int> in_city { get; set; }
        public Nullable<int> e_100 { get; set; }
        public Nullable<int> e_300 { get; set; }
        public Nullable<int> m_300 { get; set; }
        public Nullable<int> hn_dn { get; set; }
        public Nullable<int> hn_hcm { get; set; }
    }
}
